### ISSUE TITLE
protocol: nil pointer dereference

### ISSUE THREAD

**Issue by Szperak** [thinkofdeath/steven#23]
I was walking around and your gopher panicked:

```gopanic
Unhandled plugin message REGISTER
The server is running: BungeeCord (Hypixel)
Unhandled plugin message REGISTER
The server is running: BungeeCord (Hypixel) <- Spigot
MSG(0):                          
MSG(0):                          
Disconnected: dial tcp 162.159.251.33:25565: connection timed out
Write handler closed
Read handler closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5e884d]

goroutine 19259 [running]:
github.com/thinkofdeath/steven/protocol.(*Conn).ReadPacket(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:157 +0x12d
github.com/thinkofdeath/steven.startConnection(0xc208324848, 0x6, 0xc20990c2c0, 0x20, 0xc20990c240, 0x20, 0xc20871a390, 0xe)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/network.go:67 +0x318
created by github.com/thinkofdeath/steven.connect
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/steven.go:95 +0x74

goroutine 1 [runnable, locked to thread]:
github.com/thinkofdeath/steven/render.(*UIElement).appendVertex(0xc20fd6a400, 0x3fe34fe7b60773c9, 0x3fbe0f83e0f83e0e, 0x100008)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/render/ui.go:167
github.com/thinkofdeath/steven/render.(*UIElement).draw(0xc20fd6a400)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/render/ui.go:163 +0x182
github.com/thinkofdeath/steven/render.drawUI()
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/render/ui.go:68 +0xc1
github.com/thinkofdeath/steven/render.Draw(0x73f, 0x420, 0x3fe87d721ba64eb4)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/render/render.go:217 +0x11ab
github.com/thinkofdeath/steven.draw()
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/steven.go:239 +0x465
github.com/thinkofdeath/steven.startWindow()
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/desktop.go:68 +0x29b
github.com/thinkofdeath/steven.Main(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/steven.go:89 +0x134
main.main()
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/cmd/steven/steven.go:43 +0x257

goroutine 17 [syscall, 17 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 19137 [IO wait]:
net.(*pollDesc).Wait(0xc20c12fbf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20c12fbf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20c12fb90, 0xc20c558000, 0x1000, 0x1000, 0x0, 0x7f3bcb3b1360, 0xc20c70f848)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209d300a8, 0xc20c558000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f3bcb3b26c0, 0xc209d300a8, 0xc20806d2e8, 0xc20c558000, 0x1000, 0x1000, 0x87bd60, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20b8ab5e0, 0xc20c558000, 0x1000, 0x1000, 0xc208518900, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20bfb6960)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20bfb6960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806d290)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 19608 [IO wait]:
net.(*pollDesc).Wait(0xc20b46b090, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b46b090, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b46b030, 0xc20c246000, 0x200, 0x200, 0x0, 0x7f3bcb3b1360, 0xc20bc50088)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20c220030, 0xc20c246000, 0x200, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net.(*UDPConn).readDNSResponse(0xc20c220030, 0xc20b960000, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:43 +0xae
net.exchange(0xc20bc50020, 0xc, 0xc20c73c020, 0x1d, 0xc20bc50021, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:146 +0x471
net.tryOneName(0xc20844afa0, 0xc20c73c020, 0x1d, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:175 +0x46e
net.lookup(0xc20c73c000, 0x1c, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:299 +0x79a
net.lookupSRV(0x9a63d0, 0x9, 0x98a3a0, 0x3, 0xc208ab4cf0, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup_unix.go:95 +0x10e
net.LookupSRV(0x9a63d0, 0x9, 0x98a3a0, 0x3, 0xc208ab4cf0, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:120 +0xba
github.com/thinkofdeath/steven/protocol.Dial(0xc208ab4cf0, 0xc, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:66 +0xbb
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc2088dc340, 0xc208ab4cf0, 0xc, 0xc209d5ee80, 0xc2099567e0, 0xc20c74a860, 0x1f, 0xc209956870, 0xc209956900)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:213 +0x12c
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e

goroutine 19609 [IO wait]:
net.(*pollDesc).Wait(0xc20b46b800, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b46b800, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b46b7a0, 0xc20c246200, 0x200, 0x200, 0x0, 0x7f3bcb3b1360, 0xc20bc50120)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20c220078, 0xc20c246200, 0x200, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net.(*UDPConn).readDNSResponse(0xc20c220078, 0xc20b960080, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:43 +0xae
net.exchange(0xc20bc500c0, 0xc, 0xc20c73c160, 0x1f, 0xc20bc50021, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:146 +0x471
net.tryOneName(0xc20844afa0, 0xc20c73c160, 0x1f, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:175 +0x46e
net.lookup(0xc20c73c140, 0x1e, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:299 +0x79a
net.lookupSRV(0x9a63d0, 0x9, 0x98a3a0, 0x3, 0xc20871a390, 0xe, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup_unix.go:95 +0x10e
net.LookupSRV(0x9a63d0, 0x9, 0x98a3a0, 0x3, 0xc20871a390, 0xe, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:120 +0xba
github.com/thinkofdeath/steven/protocol.Dial(0xc20871a390, 0xe, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:66 +0xbb
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc2088dc340, 0xc20871a390, 0xe, 0xc209d5f000, 0xc209956cf0, 0xc20c74a9e0, 0x1f, 0xc209956e10, 0xc209956ea0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:213 +0x12c
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e

goroutine 19394 [select]:
net/http.(*persistConn).writeLoop(0xc209cd02c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 986 [sleep]:
net.func·019()
	/usr/local/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/usr/local/go/src/net/dnsclient_unix.go:269 +0x20c

goroutine 19297 [IO wait]:
net.(*pollDesc).Wait(0xc20b46b720, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b46b720, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b46b6c0, 0xc208fac000, 0x1000, 0x1000, 0x0, 0x7f3bcb3b1360, 0xc209bb81e8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209a42048, 0xc208fac000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f3bcb3b26c0, 0xc209a42048, 0xc209cd0318, 0xc208fac000, 0x1000, 0x1000, 0x87bd60, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208e500e0, 0xc208fac000, 0x1000, 0x1000, 0xc208519b00, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2093c4180)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2093c4180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc209cd02c0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 19378 [select]:
net/http.(*persistConn).writeLoop(0xc20806d290)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 19227 [IO wait]:
net.(*pollDesc).Wait(0xc208011f00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011f00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208011ea0, 0xc209e10400, 0x400, 0x400, 0x0, 0x7f3bcb3b1360, 0xc208c5a240)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208284048, 0xc209e10400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20c794a80, 0x7f3bcb3b26c0, 0xc208284048, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208fe0000, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208fe0000, 0xc20abfa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f3bcb3b72c0, 0xc208fe0000, 0xc20de9c3c8, 0xc20abfa000, 0x1000, 0x1000, 0xc20bc4e140, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20ab95700, 0xc20abfa000, 0x1000, 0x1000, 0xc208015600, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20dcfb320)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20dcfb320, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20de9c370)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 19228 [select]:
net/http.(*persistConn).writeLoop(0xc20de9c370)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 19250 [IO wait]:
net.(*pollDesc).Wait(0xc20c341bf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20c341bf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20c341b90, 0xc20ba2e27c, 0x1, 0x1, 0x0, 0x7f3bcb3b1360, 0xc20ba2e290)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20c220038, 0xc20ba2e27c, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
github.com/thinkofdeath/steven/protocol.ReadByte(0x7f3bcb3b26c0, 0xc20c220038, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/io.go:191 +0x109
github.com/thinkofdeath/steven/protocol.ReadVarInt(0x7f3bcb3b26c0, 0xc20c220038, 0xc20c220038, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/io.go:71 +0x55
github.com/thinkofdeath/steven/protocol.(*Conn).readPacket(0xc20ab6c100, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:167 +0x7a
github.com/thinkofdeath/steven/protocol.(*Conn).ReadPacket(0xc20ab6c100, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:158 +0xf4
github.com/thinkofdeath/steven/protocol.(*Conn).RequestStatus(0xc20ab6c100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/status.go:68 +0x260
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc20c5accc0, 0xc208f5a480, 0xa, 0xc20b960700, 0xc20abae1b0, 0xc208ddc340, 0x1f, 0xc20abae240, 0xc20abae2d0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:223 +0x2c4
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e

goroutine 19255 [IO wait]:
net.(*pollDesc).Wait(0xc20df98ed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20df98ed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20df98e70, 0xc20ac1125c, 0x1, 0x1, 0x0, 0x7f3bcb3b1360, 0xc20ac11270)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20bc3e090, 0xc20ac1125c, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
github.com/thinkofdeath/steven/protocol.ReadByte(0x7f3bcb3b26c0, 0xc20bc3e090, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/io.go:191 +0x109
github.com/thinkofdeath/steven/protocol.ReadVarInt(0x7f3bcb3b26c0, 0xc20bc3e090, 0xc20bc3e090, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/io.go:71 +0x55
github.com/thinkofdeath/steven/protocol.(*Conn).readPacket(0xc20abd0980, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:167 +0x7a
github.com/thinkofdeath/steven/protocol.(*Conn).ReadPacket(0xc20abd0980, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:158 +0xf4
github.com/thinkofdeath/steven/protocol.(*Conn).RequestStatus(0xc20abd0980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/status.go:68 +0x260
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc20c5accc0, 0xc208f5a480, 0xa, 0xc20dfb4700, 0xc20c75ce10, 0xc20dfb7880, 0x1f, 0xc20c75cea0, 0xc20c75cf30)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:223 +0x2c4
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e

goroutine 19607 [runnable, locked to thread]:
net._C2func_getaddrinfo(0x7f3ba00008c0, 0x0, 0xc209319408, 0xc209319358, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/:26 +0x55
net.cgoLookupIPCNAME(0xc20c66e000, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc20c680200)
	/usr/local/go/src/net/cgo_unix.go:96 +0x1c5
net.cgoLookupIP(0xc20c66e000, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x200)
	/usr/local/go/src/net/cgo_unix.go:148 +0x65
net.lookupIP(0xc20c66e000, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:64 +0x5f
net.func·025(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:41 +0x55
net.(*singleflight).doCall(0xf383c0, 0xc20bfb6000, 0xc20c66e000, 0xc, 0xc2093196d8)
	/usr/local/go/src/net/singleflight.go:91 +0x2f
net.(*singleflight).Do(0xf383c0, 0xc20c66e000, 0xc, 0xc2093196d8, 0x0, 0x0, 0x0, 0x0, 0x43a4f8)
	/usr/local/go/src/net/singleflight.go:61 +0x280
net.lookupIPMerge(0xc20c66e000, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:42 +0xae
net.lookupIPDeadline(0xc20c66e000, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:64 +0x12d
net.resolveInternetAddr(0x98a3a0, 0x3, 0xc20c66e000, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0x983bc0, 0x4, 0x98a3a0, 0x3, 0xc20c66e000, 0x12, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc209a2c040, 0x98a3a0, 0x3, 0xc20c66e000, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:158 +0xf6
net.Dial(0x98a3a0, 0x3, 0xc20c66e000, 0x12, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:143 +0x8a
github.com/thinkofdeath/steven/protocol.Dial(0xc20c66e000, 0x12, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:74 +0x2b0
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc2088dc340, 0xc20abc1ef0, 0xc, 0xc209d5ed00, 0xc209956360, 0xc20c74a700, 0x1f, 0xc2099563f0, 0xc209956480)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:213 +0x12c
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e

goroutine 17729 [IO wait, 2 minutes]:
net.(*pollDesc).Wait(0xc2087e8df0, 0x77, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc2087e8df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).connect(0xc2087e8d90, 0x0, 0x0, 0x7f3bcb3b16b0, 0xc20bdba560, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:114 +0x24b
net.(*netFD).dial(0xc2087e8d90, 0x7f3bcb3b1660, 0x0, 0x7f3bcb3b1660, 0xc20bb825a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/sock_posix.go:139 +0x37a
net.socket(0x98a3a0, 0x3, 0x2, 0x1, 0x0, 0xc20bb82500, 0x7f3bcb3b1660, 0x0, 0x7f3bcb3b1660, 0xc20bb825a0, ...)
	/usr/local/go/src/net/sock_posix.go:91 +0x422
net.internetSocket(0x98a3a0, 0x3, 0x7f3bcb3b1660, 0x0, 0x7f3bcb3b1660, 0xc20bb825a0, 0x0, 0x0, 0x0, 0x1, ...)
	/usr/local/go/src/net/ipsock_posix.go:137 +0x148
net.dialTCP(0x98a3a0, 0x3, 0x0, 0xc20bb825a0, 0x0, 0x0, 0x0, 0xc20bdba520, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:156 +0x125
net.dialSingle(0x98a3a0, 0x3, 0xc20bdba4c0, 0x11, 0x0, 0x0, 0x7f3bcb3b15d0, 0xc20bb825a0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:235 +0x3f5
net.func·016(0x0, 0xc200000000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:163 +0x12c
net.dial(0x98a3a0, 0x3, 0x7f3bcb3b15d0, 0xc20bb825a0, 0xc20c20fc98, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:40 +0x6f
net.(*Dialer).Dial(0xc2093da100, 0x98a3a0, 0x3, 0xc20bdba4c0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:170 +0x4be
net.Dial(0x98a3a0, 0x3, 0xc20bdba4c0, 0x11, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:143 +0x8a
github.com/thinkofdeath/steven/protocol.Dial(0xc20bdba4c0, 0x11, 0x3, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:74 +0x2b0
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc209bb6240, 0xc20bdbdec0, 0xb, 0xc20c552500, 0xc20b7ff3b0, 0xc20bf45dc0, 0x1f, 0xc20b7ff440, 0xc20b7ff4d0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:213 +0x12c
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e

goroutine 19606 [runnable, locked to thread]:
net._C2func_getaddrinfo(0x7f3b800008c0, 0x0, 0xc20c393408, 0xc20c393358, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/:26 +0x55
net.cgoLookupIPCNAME(0xc20c515880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc20abcd400)
	/usr/local/go/src/net/cgo_unix.go:96 +0x1c5
net.cgoLookupIP(0xc20c515880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x200)
	/usr/local/go/src/net/cgo_unix.go:148 +0x65
net.lookupIP(0xc20c515880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:64 +0x5f
net.func·025(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:41 +0x55
net.(*singleflight).doCall(0xf383c0, 0xc20bf24240, 0xc20c515880, 0xa, 0xc20c3936d8)
	/usr/local/go/src/net/singleflight.go:91 +0x2f
net.(*singleflight).Do(0xf383c0, 0xc20c515880, 0xa, 0xc20c3936d8, 0x0, 0x0, 0x0, 0x0, 0x43a4f8)
	/usr/local/go/src/net/singleflight.go:61 +0x280
net.lookupIPMerge(0xc20c515880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:42 +0xae
net.lookupIPDeadline(0xc20c515880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:64 +0x12d
net.resolveInternetAddr(0x98a3a0, 0x3, 0xc20c515880, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0x983bc0, 0x4, 0x98a3a0, 0x3, 0xc20c515880, 0x10, 0x0, 0xc200000000, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc20bdcc3c0, 0x98a3a0, 0x3, 0xc20c515880, 0x10, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:158 +0xf6
net.Dial(0x98a3a0, 0x3, 0xc20c515880, 0x10, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:143 +0x8a
github.com/thinkofdeath/steven/protocol.Dial(0xc20c515880, 0x10, 0x18400, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/protocol/connection.go:74 +0x2b0
github.com/thinkofdeath/steven.(*serverList).pingServer(0xc2088dc340, 0xc208f5a480, 0xa, 0xc209d5eb80, 0xc209957e60, 0xc20c74a5a0, 0x1f, 0xc209957ef0, 0xc209956d80)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:213 +0x12c
created by github.com/thinkofdeath/steven.(*serverList).redraw
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/ui_serverlist.go:177 +0xf5e
```

Steven is running on linux (on 8GB pendrive).

**Comment by thinkofdeath** [comment]
Are you on latest? The line numbers don't make sense to me

**Comment by Szperak** [comment]
I downloaded a release from http://ci.thinkofdeath.co.uk/viewType.html?buildTypeId=Steven_Client&guest=1

**Comment by Szperak** [comment]
I don't have installed go on my linux (or even java).
