### ISSUE TITLE
all: race somewhere

### ISSUE THREAD

**Issue by thinkofdeath** [thinkofdeath/steven#24]
Randomly there are crashes (normally very shortly after startup) that can range from sigsegv to faults. I'm pretty sure there is a race condition somewhere causing this but i'm unable to run the race detector due to golang/go#10874 so this will have to wait until thats fixed

**Comment by thinkofdeath** [comment]
```
unexpected fault address 0x1818082c5
fatal error: fault
[signal 0xb code=0x1 addr=0x1818082c5 pc=0x1818082c5]

goroutine 1 [running, locked to thread]:
runtime.throw(0x9f14e0, 0x5)
	/home/matt/go/src/runtime/panic.go:527 +0x96 fp=0xc20876f7c8 sp=0xc20876f7b0
runtime.sigpanic()
	/home/matt/go/src/runtime/sigpanic_unix.go:27 +0x2ae fp=0xc20876f818 sp=0xc20876f7c8
```

**Comment by thinkofdeath** [comment]
Doesn't seem to happen with newer go builds, closing
