### ISSUE TITLE
Steven Crashes (Windows)

### ISSUE THREAD

**Issue by Ajusa** [thinkofdeath/steven#61]
This is the precompilled build
steven.log:
```
[blocktint.go:40] loading biome colors: file not found
[blocktint.go:40] loading biome colors: file not found
[resource.go:278] Obtaining vanilla resources for 1.8.7, please wait...
```
steven-error.log:
```
panic: VersionUnavailable: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable

goroutine 1 [running, locked to thread]:
github.com/thinkofdeath/steven.startWindow()
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/desktop.go:75 +0x1c1
github.com/thinkofdeath/steven.Main(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/steven.go:94 +0x13e
main.main()
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/cmd/steven/steven.go:47 +0x280

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/thinkofdeath/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 34 [select]:
net/http.(*Transport).getConn(0xc082058120, 0xc08220a000, 0x0, 0xc082496460, 0x5, 0xc082230060, 0x14, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/transport.go:554 +0x66a
net/http.(*Transport).RoundTrip(0xc082058120, 0xc08220a000, 0xac, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/transport.go:228 +0x4b3
net/http.send(0xc08220a000, 0x2b44440, 0xc082058120, 0xc0824964b0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/client.go:220 +0x533
net/http.(*Client).send(0xe40be0, 0xc08220a000, 0x44, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/client.go:143 +0x161
net/http.(*Client).doFollowingRedirects(0xe40be0, 0xc08220a000, 0xbffaf0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/client.go:380 +0xbc7
net/http.(*Client).Get(0xe40be0, 0xc082496460, 0x44, 0xc082208000, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/client.go:306 +0xb1
net/http.Get(0xc082496460, 0x44, 0xc082203ea8, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/client.go:281 +0x4c
github.com/thinkofdeath/steven/resource.downloadDefault(0xc08241cb20, 0xc0820124e0, 0xc082234e60, 0x11)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/resource/resource.go:279 +0x24e
github.com/thinkofdeath/steven/resource.Init.func1(0xc0820124e0, 0xc08241cb20, 0xc082234e60, 0x11)
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/resource/resource.go:158 +0xad
created by github.com/thinkofdeath/steven/resource.Init
	/home/thinkofdeath/TeamCity/buildAgent/work/9213002c05b9c4f1/src/github.com/thinkofdeath/steven/resource/resource.go:165 +0x2b5

goroutine 19 [select]:
net.lookupIPDeadline(0xc082230060, 0x10, 0xecd3e588b, 0x39ca9994, 0xe40d20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/lookup.go:109 +0x6ac
net.internetAddrList(0xacffd0, 0x3, 0xc082230060, 0x14, 0xecd3e588b, 0x39ca9994, 0xe40d20, 0x0, 0x0, 0x0, ...)
	/home/thinkofdeath/go/src/net/ipsock.go:252 +0x6f5
net.resolveAddrList(0xacdcc0, 0x4, 0xacffd0, 0x3, 0xc082230060, 0x14, 0xecd3e588b, 0x39ca9994, 0xe40d20, 0x0, ...)
	/home/thinkofdeath/go/src/net/dial.go:154 +0x46d
net.(*Dialer).Dial(0xc0820105a0, 0xacffd0, 0x3, 0xc082230060, 0x14, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/dial.go:208 +0x114
net.(*Dialer).Dial-fm(0xacffd0, 0x3, 0xc082230060, 0x14, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/transport.go:38 +0x75
net/http.(*Transport).dial(0xc082058120, 0xacffd0, 0x3, 0xc082230060, 0x14, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/transport.go:499 +0x80
net/http.(*Transport).dialConn(0xc082058120, 0x0, 0xc082496460, 0x5, 0xc082230060, 0x14, 0x9f0101, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/http/transport.go:596 +0x1adb
net/http.(*Transport).getConn.func4(0xc082058120, 0x0, 0xc082496460, 0x5, 0xc082230060, 0x14, 0xc0824ee060)
	/home/thinkofdeath/go/src/net/http/transport.go:549 +0x6d
created by net/http.(*Transport).getConn
	/home/thinkofdeath/go/src/net/http/transport.go:551 +0x26c

goroutine 20 [syscall, locked to thread]:
syscall.Syscall6(0x7fefd8e23c0, 0x4, 0xc082233050, 0x0, 0xc08249bdd0, 0xc08249bc80, 0x0, 0x0, 0x10, 0xc082233050, ...)
	/home/thinkofdeath/go/src/runtime/syscall_windows.go:139 +0x5f
syscall.GetAddrInfoW(0xc082233050, 0x0, 0xc08249bdd0, 0xc08249bc80, 0x0, 0x0)
	/home/thinkofdeath/go/src/syscall/zsyscall_windows.go:1670 +0x96
net.newLookupIP(0xc082230060, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/lookup_windows.go:118 +0x152
net.glob.func15(0xbff9e8, 0xc082230060, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/hook.go:10 +0x54
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/home/thinkofdeath/go/src/net/lookup.go:106 +0x78
internal/singleflight.(*Group).doCall(0xe3ffc0, 0xc082496500, 0xc082230060, 0x10, 0xc082230160)
	/home/thinkofdeath/go/src/internal/singleflight/singleflight.go:93 +0x33
created by internal/singleflight.(*Group).DoChan
	/home/thinkofdeath/go/src/internal/singleflight/singleflight.go:86 +0x3f4
```
I don't quite know what is going on...
When I tried building, I got an error saying:
# github.com/thinkofdeath/steven/audio
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
# github.com/go-gl/glfw/v3.1/glfw
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
# github.com/thinkofdeath/gl/v3.2-core/gl
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

I am a newbie to golang in general, but I have used it before. My graphics card is Intel HD Graphics 3000, and I am running Windows 7, 64 Bit. Sorry if this is due to my utter incompetence when it comes to building things.

**Comment by thinkofdeath** [comment]
That error is caused by having a driver/gpu that doesn't support opengl 3 as far as I know.

As for the build error you have a 32 bit compiler for a 64 bit version of go. mingw-w64 supports 64 bit
